### ISSUE TITLE
导入项目到AS中很容易报错，谷歌了一下有高手解决了。

### ISSUE THREAD

**Issue by ziyitony** [dss16694/WechatFp#6]
报错Gradle Sync Issues。
解决在这里http://blog.csdn.net/zymndsc_2012/article/details/72864736
希望作者大大先删掉库里面的  .gradle文件夹等文件，这样我们在不同的环境中能避免不兼容。
很好用，超级感谢！！！

**Comment by ziyitony** [comment]
我自己编译运行这个适配6.5.13版本的，结果还是失败，不显示支付指纹，然后安装了6.5.10，才可以用。不知道是不是我自己哪里没弄对。我没有修改代码，可能修改了gradle里面的某些值。

**Comment by dss16694** [comment]
我用的OK啊，只做了6.5.13国内版的，play版不支持

**Comment by dss16694** [comment]
另外，实在是菜鸟一个，github不大会用，studio也不大会用，只是简单的分享一下代码，其他问题需要你们自己解决，^_^

**Comment by ziyitony** [comment]
真的非常感谢你！
