### ISSUE TITLE
一点代码上的建议

### ISSUE THREAD

**Issue by liberize** [dss16694/WechatFp#7]
https://github.com/dss16694/WechatFp/blob/master/app/src/main/java/com/yyxx/wechatfp/ObfuscationHelper.java
打算长期维护的话，是不是用一个 switch...case... 比较好，不然后面版本多了，代码很难看。比如可以参考：
https://github.com/veryyoung/WechatLuckyMoney/blob/master/app/src/main/java/me/veryyoung/wechat/luckymoney/VersionParam.java

**Comment by dss16694** [comment]
多谢提醒，后面改一下。
没有系统的学过编程，只是看了一本叫Android从入门到精通，所以很不专业，汗
